name: uav_combat

obs_dim: 42
action_dim: 3

# 因为你目前没有 UAV 的仿真环境，不能直接用 PushTKeypointsRunner
# 我们先用一个最基础的 Runner，或者如果你之前改了代码支持 null，就写 null
env_runner:
  _target_: diffusion_policy.env_runner.uav_combat_offline_runner.UAVCombatOfflineRunner
  dataset: ${..dataset}
  batch_size: 256
  num_workers: 0
  pin_memory: True
  device: ${training.device}
  max_batches: null
  save_plots: True
  plot_dir: plots
  plot_interval: 10
  plot_num_samples: 2
  plot_action: True
  plot_curves: True
  curve_log_path: logs.json.txt

dataset:
  _target_: diffusion_policy.dataset.uav_combat_lowdim_dataset.UAVCombatLowdimDataset
  zarr_path: ${hydra:runtime.cwd}/data/uav_combat/test_data_mode_switch.zarr
  horizon: ${horizon}
  # 只采真实窗口，不对序列头尾做重复填充
  pad_before: 0
  pad_after: 0
  seed: 42
  val_ratio: 0.1
